# Name shown in GitHub Actions UI
# You can call this anything
# Example: terraform, deploy-infra, gcp-deployment
name: terraform

# Event that triggers this workflow
on:

  # Whenever code is pushed
  push:

    # Only if the push is to the main branch
    branches:
      - main

# ==========================================================
# Required for Workload Identity Federation
#
# id-token: write
#   Allows GitHub to generate an OIDC token.
#
# contents: read
#   Allows workflow to read repository contents.
#
# Without id-token: write:
#   google-github-actions/auth will fail.
# ==========================================================
permissions:
  id-token: write
  contents: read

# A workflow can have multiple jobs
# Example:
# jobs:
#   terraform:
#   deploy-airflow:
#   deploy-spark:
#
# Here we only have one job
jobs:

  # Job name
  # Does NOT need to match workflow name
  #
  # This is simply an identifier
  terraform:

    # GitHub creates a temporary VM for this job
    #
    # ubuntu-latest means:
    # "Give me the newest supported Ubuntu machine"
    #
    # Currently usually Ubuntu 24 or 22
    #
    # GitHub provisions:
    # CPU
    # RAM
    # Network
    # Temporary disk
    #
    # Job runs on that machine
    runs-on: ubuntu-latest

    # Default location for all commands
    #
    # Instead of:
    #
    # run: cd terraform/environments/dev
    # run: terraform init
    #
    # every step automatically executes here
    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      # Step 1
      #
      # Downloads your GitHub repository
      # into the temporary VM
      #
      # Without this step:
      # there is no terraform code available
      - name: Checkout Repository
        uses: actions/checkout@v4

     # ----------------------------------------------------
      # Step 2
      #
      # Authenticate GitHub to GCP.
      #
      # Uses Workload Identity Federation.
      #
      # No JSON key file required.
      #
      # Flow:
      #
      # GitHub
      #    ↓
      # OIDC Token
      #    ↓
      # Workload Identity Pool
      #    ↓
      # Service Account
      #    ↓
      # Temporary GCP Credentials
      # ----------------------------------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:

          # Full Workload Identity Provider path.
          #
          # Example:
          # projects/123456789/locations/global/
          # workloadIdentityPools/github-pool/
          # providers/github-provider
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

          # Service account to impersonate.
          #
          # Example:
          # github-actions@
          # marketing-analytics-pam.iam.gserviceaccount.com
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # ----------------------------------------------------

      # Step 3
      #
      # Install Terraform binary
      #
      # Similar to:
      #
      # brew install terraform
      #
      # but inside the temporary VM
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
      # Step 4
      #
      # Download providers
      #
      # Example:
      # Google Provider
      #
      # Configure backend
      #
      # Read terraform state
      #
      # Must run before plan/apply
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
      # Step 5
      #
      # Calculate changes
      #
      # Example:
      # + create bucket
      # + create dataproc cluster
      #
      # No changes made yet
      - name: Terraform Plan
        run: terraform plan

      # Step 6
      #
      # Execute the plan
      #
      # Infrastructure actually gets created
      #
      # auto-approve skips
      # manual confirmation
      - name: Terraform Apply
        run: terraform apply -auto-approve